"use client";
import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { Check } from "lucide-react";
import { CAPTION_PRESETS, CLIP_LENGTHS, DEFAULT_GENERATION, parseGeneration, type GenerationSettings } from "@/lib/video-workspace/generation-settings";
import type { SelectionRequirements } from "@/lib/video-workspace/selection";
const DEFAULTS_KEY = "scribix:clip-generation:v1";
export function GenerationSettingsPanel({ projectId, value, onChange, disabled, durationMs }: { projectId: string; value: SelectionRequirements; onChange: (value: SelectionRequirements) => void; disabled: boolean; durationMs: number }) {
  const t = useTranslations("ClipWorkflow");
  const [saved, setSaved] = useState(false);
  const settings = value.generation ?? DEFAULT_GENERATION;
  useEffect(() => { if (!value.generation && !disabled) { try { const stored = localStorage.getItem(DEFAULTS_KEY); if (stored) onChange({ ...value, generation: parseGeneration(JSON.parse(stored)) }); } catch { /* Invalid or unavailable browser defaults are optional. */ } } }, []);
  const update = (next: Partial<GenerationSettings>) => { setSaved(false); onChange({ ...value, generation: { ...settings, ...next } }); };
  return <fieldset disabled={disabled} className="mt-6 space-y-6 border-t border-line pt-6 disabled:opacity-60">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-display text-title font-semibold tracking-tight">{t("settings")}</h3><p className="mt-1 text-sm text-muted">{t("settingsHelp")}</p></div><span className="rounded-lg border border-line px-3 py-2 font-mono text-xs">{t("portrait", {ratio:"9:16"})}</span></div>
    <div className="grid gap-6 sm:grid-cols-[180px_minmax(0,1fr)]"><div className="relative mx-auto aspect-[9/16] w-44 overflow-hidden rounded-xl bg-black"><video src={`/api/video-projects/${projectId}/source?format=media`} muted playsInline preload="metadata" controls className={`size-full ${settings.framing==="fit"?"object-contain":"object-cover"}`}/>{settings.captions!=="none" ? <span aria-hidden className={`pointer-events-none absolute inset-x-3 bottom-20 text-center text-sm font-semibold ${settings.captions==="boxed-v1"?"rounded bg-white px-2 py-1 text-black":settings.captions==="karaoke-v1"?"uppercase text-yellow-300 [text-shadow:0_1px_3px_black]":"text-white [text-shadow:0_1px_3px_black]"}`}>{t("sample")}</span>:null}</div><div className="grid content-center gap-6"><label className="text-sm font-medium">{t("length")}<select value={settings.length} onChange={e=>update({length:e.target.value as GenerationSettings["length"]})} className="mt-2 block w-full rounded-control border border-line bg-paper p-3 text-body-sm">{Object.entries(CLIP_LENGTHS).map(([id,[min,max]])=><option key={id} value={id}>{t(id==="auto" ? "autoLength" : "lengthRange",{min,max})}</option>)}</select></label><label className="text-sm font-medium">{t("framing")}<select value={settings.framing} onChange={e=>update({framing:e.target.value as GenerationSettings["framing"]})} className="mt-2 block w-full rounded-control border border-line bg-paper p-3 text-body-sm"><option value="auto">{t("autoFrame")}</option><option value="fit">{t("fullFrame")}</option></select></label></div></div>
    <div><h4 className="mb-3 text-sm font-medium">{t("captions")}</h4><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{CAPTION_PRESETS.map(preset=><button type="button" key={preset} aria-pressed={settings.captions===preset} onClick={()=>update({captions:preset})} className="overflow-hidden rounded-control border border-line text-left transition hover:border-accent aria-pressed:border-accent aria-pressed:ring-2 aria-pressed:ring-accent/25"><div className="relative flex aspect-[4/3] items-end justify-center overflow-hidden bg-black p-3 text-center text-white"><span className={`mb-3 text-sm font-semibold ${preset==="boxed-v1" ? "rounded bg-white px-2 py-1 text-black" : preset==="karaoke-v1" ? "font-bold uppercase text-yellow-300" : "font-normal"}`}>{preset!=="none" ? t("sample") : <span className="text-white/40">{t("noCaptions")}</span>}</span></div><span className="flex items-center justify-between p-3 text-xs font-semibold">{t(`preset.${preset}`)}{settings.captions===preset ? <Check size={15}/> : null}</span></button>)}</div><p className="mt-2 text-xs text-muted">{t("styleExample")}</p></div>
    <label className="flex items-start gap-3 rounded-control border border-line p-4"><input type="checkbox" checked={settings.headline} onChange={e=>update({headline:e.target.checked})} className="mt-1 accent-[var(--accent)]"/><span><span className="block text-sm font-medium">{t("headline")}</span><span className="mt-1 block text-xs text-muted">{t("headlineHelp")}</span></span></label>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4"><p className="max-w-lg text-xs leading-5 text-muted">{t("usage",{minutes:Math.ceil(durationMs/60000)})}</p><button type="button" onClick={()=>{try{localStorage.setItem(DEFAULTS_KEY,JSON.stringify(settings));setSaved(true);}catch{setSaved(false);}}} className="rounded-lg border border-line px-3 py-2 text-xs font-medium">{t(saved ? "defaultsSaved" : "saveDefaults")}</button></div>
  </fieldset>;
}
